site:
  title: Hello World!
  start_page: HuyenTestAsciiDoc6.3.2023::index.adoc
content:
  sources:
      - url: https://github.com/HuyenNguyen238/repodemo6.3.2023
    start_paths: index.adoc
    output: html